#!/bin/bash -e

set -Eeo pipefail

AWS_REGION=eu-west-2
AWS_DEFAULT_REGION=$AWS_REGION
DOCKER_REGISTRY=327778747031.dkr.ecr.eu-west-2.amazonaws.com
PRM_REPO_MHS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
if [[ -z "$GO_MATERIAL_URL_MHS" ]]; then
  INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY="${INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY:-integration-adaptor-mhs}"
else
  # we are running on gocd. use a material checkout next to current repo
  INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY="$PRM_REPO_MHS_DIR/../integration-adaptor-mhs"
fi

if [[ ! -d $INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY ]]; then
  echo "You need a checkout of integration-adaptor-mhs. If you have one, set the path in INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY"
fi

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function docker_login {
  eval $(dojo "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

function build_dns_overlay {
  BASE_IMAGE=$1
  BUILT_IMAGE_URL=$2
  cd $PRM_REPO_MHS_DIR/docker-scripts
  docker build \
    -t $BUILT_IMAGE_URL \
    --build-arg BASE_IMAGE=$BASE_IMAGE .
}

command="$1"
case "${command}" in
  build_docker)
    IMAGE_PREFIX=$2
    if [ -z "$IMAGE_PREFIX" ]; then
      echo "Please specify one of the images to be built: inbound, outbound, or route"
      exit 5
    fi
    UPSTREAM_GIT_HASH=$(cd $INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY && git rev-parse HEAD | cut -c 1-8)
    REPO_GIT_HASH=$(git rev-parse HEAD | cut -c 1-8)
    BUILD_TAG="${UPSTREAM_GIT_HASH}-${REPO_GIT_HASH}"
    if [[ "$local_build" != "true" ]]; then
      docker_login
    fi
    #TODO build base image first
    BASE_IMAGE_TAG="${BASE_IMAGE_TAG:-1.0.1}"
    cd $INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY
    DOCKER_DIRECTORY=$IMAGE_PREFIX
    if [[ $IMAGE_PREFIX == "route" ]]; then
      DOCKER_DIRECTORY=spineroutelookup
    fi
    docker build \
     --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG \
     -t mhs-${IMAGE_PREFIX}:$BUILD_TAG \
     -f mhs/$DOCKER_DIRECTORY/Dockerfile .

    build_dns_overlay mhs-${IMAGE_PREFIX}:$BUILD_TAG $DOCKER_REGISTRY/mhs-${IMAGE_PREFIX}:$BUILD_TAG
    docker run --rm -v $PRM_REPO_MHS_DIR:/test --entrypoint sh $DOCKER_REGISTRY/mhs-${IMAGE_PREFIX}:$BUILD_TAG -c "openssl verify -verbose /test/test-assets/sds-ldaps.crt"

    if [[ "$local_build" != "true" ]]; then
      docker push $DOCKER_REGISTRY/mhs-${IMAGE_PREFIX}:$BUILD_TAG
    fi
    ;;
  unit_test)
    MHS_COMPONENT=$2
    if [ -z "$MHS_COMPONENT" ]; then
      echo "Please specify one of the components to test: inbound, outbound, or route"
      exit 5
    fi
    if [[ $MHS_COMPONENT == "route" ]]; then
      MHS_DIRECTORY=spineroutelookup
    fi
    cd $INTEGRATION_ADAPTORS_MHS_REPO_DIRECTORY
    dojo -c ${PRM_REPO_MHS_DIR}/Dojofile-py "cd mhs/$MHS_DIRECTORY && pipenv install --dev && pipenv run unittests"
    ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
