format_version: 4
pipelines:
  "prm-repo-mhs":
    group: mhs
    label_template: "${mhs[:8]}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-repo-mhs
      mhs:
        git: https://github.com/nhsconnect/integration-adaptor-mhs.git
        branch: feature/NIAD-1487-sds-api-test
        # git: https://github.com/tomzo-nhs/integration-adaptor-mhs.git
        # branch: mhs-outbound-with-sds
        destination: integration-adaptor-mhs
    stages:
      - build_docker:
          clean_workspace: true
          jobs:
            outbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker outbound
            inbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker inbound
