format_version: 4
pipelines:
  "prm-repo-mhs":
    group: mhs
    label_template: "${mhs[:8]}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-repo-mhs
      mhs:
        git: https://github.com/nhsconnect/integration-adaptor-mhs.git
        branch: develop
        destination: integration-adaptor-mhs
    stages:
      - test:
          clean_workspace: true
          jobs:
            outbound:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks unit_test outbound
            inbound:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks unit_test inbound
      - build_docker:
          clean_workspace: true
          jobs:
            outbound:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker outbound
            inbound:
              resources:
                - docker
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker inbound
