format_version: 4
pipelines:
  prm-repo-mhs:
    group: mhs
    label_template: "${COUNT}-${mhs[:8]}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-repo-mhs
      mhs:
        git: https://github.com/nhsconnect/integration-adaptor-mhs.git
        branch: main
        destination: integration-adaptor-mhs
    stages:
      - build_docker:
          clean_workspace: true
          jobs:
            outbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker outbound
            inbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker inbound
