format_version: 4
pipelines:
  prm-repo-mhs:
    group: mhs
    label_template: "${COUNT}-${git[:8]}"
    materials:
      git:
        type: configrepo
        destination: prm-repo-mhs
#      mhs:
#        git: https://github.com/nhsconnect/integration-adaptor-mhs.git
#        branch: feature/NIAD-1487-sds-api-test
#        destination: integration-adaptor-mhs
#        git: https://github.com/danmoorenhs/integration-adaptor-mhs-patched.git
#        branch: PRMT-2752-ehr-out-fixes
    stages:
      - build_docker:
          clean_workspace: true
          jobs:
            outbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks import_docker outbound
            inbound:
              resources:
                - docker
              artifacts:
                - build:
                    source: prm-repo-mhs/imagerc
                    destination:
              tasks:
                - exec:
                    working_directory: prm-repo-mhs
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks import_docker inbound
